version: '3'
services:
  mtproto:
    build: .
    environment:
      - SECRET=  # خالی بذار تا خودش تولید کنه
    ports:
      - "443:443/tcp"
    volumes:
      - ./data:/app/data  # برای ذخیره Secret بین اجراها
